import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import ReduxProvider from '../store/ReduxProvider';
import './globals.css';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={`${roboto.variable}, bg-[#fafafa]`}>{children}</body>
      </ReduxProvider>
    </html>
  );
}
